title: Lhaíslla Cavalcanti
theme: minima 
author: lhaislla
email: lhaislla@gmail.com
description: Este é um repositorio para os meus projetos e processos de aprendizado.

# social links
twitter_username:
github_username:  https://github.com/lhaislla

show_excerpts: true # set to false to remove excerpts on the homepage
